# Initialize the kernel
/run/initialize

/gps/particle   {pName}

/gps/ene/type   User
/gps/hist/type  energy

####################################################################################################
# Input spectra from histogram file here

{histo}

####################################################################################################

/gps/pos/type   Point
/gps/pos/centre 0 0 0 cm


/gps/number   1
/gps/ang/type iso

/run/beamOn 1
